// Central mock data for LTS Car Rental.
// Replace `image` paths with real photos in /public/cars, /public/brands etc.

export const CONTACT = {
  phone: "+971 52 237 5439",
  whatsapp: "+971 52 237 5439",
  telegram: "+971 52 237 5439",
  email: "booking@lts-car-rental.com",
  address: "Sheikh Zayed Road, Business Bay, Dubai, UAE",
  domain: "lts-car-rental.com",
};

export const categories = [
  { slug: "luxury", name: "Luxury" },
  { slug: "economy", name: "Economy" },
  { slug: "sports", name: "Sports" },
  { slug: "suv", name: "SUV" },
  { slug: "convertible", name: "Convertible" },
  { slug: "business", name: "Business" },
  { slug: "electric", name: "Electric" },
  { slug: "van", name: "Van" },
];

export const brands = [
  { slug: "lamborghini", name: "Lamborghini" },
  { slug: "ferrari", name: "Ferrari" },
  { slug: "rolls-royce", name: "Rolls-Royce" },
  { slug: "bentley", name: "Bentley" },
  { slug: "mercedes-benz", name: "Mercedes-Benz" },
  { slug: "range-rover", name: "Range Rover" },
  { slug: "porsche", name: "Porsche" },
  { slug: "bmw", name: "BMW" },
];

export const bodyTypes = ["Coupe", "Sedan", "SUV", "Convertible", "Van"];
export const transmissions = ["Automatic", "Manual"];

export const cars = [
  {
    slug: "lamborghini-huracan-evo",
    name: "Lamborghini Huracán EVO",
    brand: "lamborghini",
    category: "sports",
    body: "Coupe",
    year: 2024,
    color: "Grigio Telesto",
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "5.2L V10",
    power: "640 hp",
    daily: 3200, weekly: 19500, monthly: 68000, hourly: 650,
    tag: "New Arrival",
    badge: null,
    featured: true,
    image: "/cars/huracan.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Sport exhaust", "Carbon interior", "Apple CarPlay"],
  },
  {
    slug: "ferrari-roma",
    name: "Ferrari Roma",
    brand: "ferrari",
    category: "sports",
    body: "Coupe",
    year: 2023,
    color: "Rosso Corsa",
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "3.9L V8",
    power: "612 hp",
    daily: 2900, weekly: 17800, monthly: 62000, hourly: 590,
    tag: null, badge: "-10%", oldDaily: 3220,
    featured: true,
    image: "/cars/roma.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Launch control", "Premium audio"],
  },
  {
    slug: "rolls-royce-ghost",
    name: "Rolls-Royce Ghost",
    brand: "rolls-royce",
    category: "luxury",
    body: "Sedan",
    year: 2024,
    color: "Arctic White",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "6.75L V12",
    power: "563 hp",
    daily: 4500, weekly: 28000, monthly: 95000, hourly: 900,
    tag: null, badge: null,
    featured: true,
    image: "/cars/ghost.jpg",
    features: ["Chauffeur available", "Starlight headliner", "Full insurance included", "Rear lounge seating"],
  },
  {
    slug: "bentley-continental-gt",
    name: "Bentley Continental GT",
    brand: "bentley",
    category: "luxury",
    body: "Coupe",
    year: 2023,
    color: "Beluga Black",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.0L V8",
    power: "542 hp",
    daily: 2600, weekly: 15800, monthly: 54000, hourly: 520,
    tag: null, badge: "-15%", oldDaily: 3060,
    featured: true,
    image: "/cars/continental.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Rotating display", "Naim audio"],
  },
  {
    slug: "mercedes-g63-amg",
    name: "Mercedes-Benz G63 AMG",
    brand: "mercedes-benz",
    category: "suv",
    body: "SUV",
    year: 2024,
    color: "Obsidian Black",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.0L V8 Biturbo",
    power: "585 hp",
    daily: 2200, weekly: 13500, monthly: 46000, hourly: 450,
    tag: "Available now", badge: null,
    featured: true,
    image: "/cars/g63.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "AMG performance pack", "Burmester sound"],
  },
  {
    slug: "range-rover-autobiography",
    name: "Range Rover Autobiography",
    brand: "range-rover",
    category: "suv",
    body: "SUV",
    year: 2024,
    color: "Santorini Black",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.4L V8",
    power: "523 hp",
    daily: 1600, weekly: 9800, monthly: 33000, hourly: 320,
    tag: null, badge: null,
    featured: true,
    image: "/cars/rangerover.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Massage seats", "Meridian audio"],
  },
  {
    slug: "porsche-911-carrera",
    name: "Porsche 911 Carrera S",
    brand: "porsche",
    category: "sports",
    body: "Coupe",
    year: 2023,
    color: "GT Silver",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "3.0L Flat-6",
    power: "443 hp",
    daily: 1800, weekly: 11000, monthly: 38000, hourly: 360,
    tag: null, badge: "-10%", oldDaily: 2000,
    featured: false,
    image: "/cars/911.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Sport Chrono", "Bose audio"],
  },
  {
    slug: "bmw-m4-competition",
    name: "BMW M4 Competition",
    brand: "bmw",
    category: "sports",
    body: "Coupe",
    year: 2024,
    color: "Isle of Man Green",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "3.0L Twin-Turbo",
    power: "503 hp",
    daily: 1200, weekly: 7300, monthly: 25000, hourly: 240,
    tag: "Available now", badge: null,
    featured: false,
    image: "/cars/m4.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "M Sport seats", "Harman Kardon"],
  },
  {
    slug: "mercedes-s500",
    name: "Mercedes-Benz S500",
    brand: "mercedes-benz",
    category: "business",
    body: "Sedan",
    year: 2024,
    color: "Selenite Grey",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "3.0L Inline-6",
    power: "429 hp",
    daily: 1100, weekly: 6700, monthly: 23000, hourly: 220,
    tag: null, badge: null,
    featured: false,
    image: "/cars/s500.jpg",
    features: ["Chauffeur available", "Full insurance included", "Rear executive seats", "Free delivery in Dubai"],
  },
  {
    slug: "tesla-model-s-plaid",
    name: "Tesla Model S Plaid",
    brand: "bmw",
    category: "electric",
    body: "Sedan",
    year: 2024,
    color: "Pearl White",
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    engine: "Tri-Motor EV",
    power: "1020 hp",
    daily: 900, weekly: 5500, monthly: 19000, hourly: 180,
    tag: "New Arrival", badge: null,
    featured: false,
    image: "/cars/models.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Autopilot", "Free supercharging"],
  },
  {
    slug: "mercedes-maybach-s680",
    name: "Mercedes-Maybach S680",
    brand: "mercedes-benz",
    category: "luxury",
    body: "Sedan",
    year: 2024,
    color: "Emerald Green",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "6.0L V12",
    power: "612 hp",
    daily: 2400, weekly: 14600, monthly: 50000, hourly: 480,
    tag: null, badge: null,
    featured: false,
    image: "/cars/maybach.jpg",
    features: ["Chauffeur available", "Executive rear seats", "Full insurance included", "Champagne fridge"],
  },
  {
    slug: "toyota-camry",
    name: "Toyota Camry",
    brand: "bmw",
    category: "economy",
    body: "Sedan",
    year: 2024,
    color: "Silver",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "2.5L Inline-4",
    power: "203 hp",
    daily: 180, weekly: 1050, monthly: 3200, hourly: 45,
    tag: null, badge: "-20%", oldDaily: 225,
    featured: false,
    image: "/cars/camry.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Apple CarPlay", "Fuel efficient"],
  },
  {
    slug: "mercedes-v-class",
    name: "Mercedes-Benz V-Class",
    brand: "mercedes-benz",
    category: "van",
    body: "Van",
    year: 2024,
    color: "Cavansite Blue",
    seats: 7,
    transmission: "Automatic",
    fuel: "Diesel",
    engine: "2.0L Diesel",
    power: "237 hp",
    daily: 700, weekly: 4200, monthly: 14500, hourly: 140,
    tag: null, badge: null,
    featured: false,
    image: "/cars/vclass.jpg",
    features: ["Chauffeur available", "7 seats", "Full insurance included", "Captain seats"],
  },
  {
    slug: "ferrari-portofino-m",
    name: "Ferrari Portofino M",
    brand: "ferrari",
    category: "convertible",
    body: "Convertible",
    year: 2023,
    color: "Blu Corsa",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "3.9L V8",
    power: "612 hp",
    daily: 3100, weekly: 18900, monthly: 65000, hourly: 620,
    tag: null, badge: null,
    featured: false,
    image: "/cars/portofino.jpg",
    features: ["Retractable hardtop", "Full insurance included", "Free delivery in Dubai", "Magneride"],
  },
  {
    slug: "lamborghini-urus",
    name: "Lamborghini Urus",
    brand: "lamborghini",
    category: "suv",
    body: "SUV",
    year: 2024,
    color: "Giallo Auge",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.0L V8 Biturbo",
    power: "657 hp",
    daily: 2700, weekly: 16400, monthly: 56000, hourly: 540,
    tag: "Available now", badge: null,
    featured: false,
    image: "/cars/urus.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Sport mode", "Bang & Olufsen"],
  },
];

export const reviews = [
  { name: "Omar Al-Farsi", date: "May 2025", rating: 5, text: "Booked the Huracán for a weekend in Dubai. Car was spotless and delivered to my hotel on time. The whole process took ten minutes." },
  { name: "Sophie Laurent", date: "Apr 2025", rating: 5, text: "Rented a Range Rover for a month while relocating. No deposit, full insurance, and the team handled everything over WhatsApp." },
  { name: "David Chen", date: "Apr 2025", rating: 4, text: "Smooth airport transfer and a clean G63 waiting at arrivals. Pricing was transparent with no surprise charges at return." },
  { name: "Aisha Rahman", date: "Mar 2025", rating: 5, text: "Chauffeur service for a business event was flawless. Professional driver, immaculate S-Class, and easy online booking." },
  { name: "Marco Rossi", date: "Mar 2025", rating: 5, text: "Long-term lease on a Continental GT. Best rate I found in the city and free delivery across Dubai every service visit." },
  { name: "Liam Walsh", date: "Feb 2025", rating: 4, text: "Quick weekend rental on the 911. Easy pickup in Dubai Marina and the car drove like new. Will book again next trip." },
];

export const locations = [
  { area: "Dubai Marina", count: "120+" },
  { area: "Downtown Dubai", count: "95+" },
  { area: "Business Bay", count: "110+" },
  { area: "Palm Jumeirah", count: "70+" },
  { area: "Jumeirah Beach Residence", count: "85+" },
  { area: "DIFC", count: "60+" },
  { area: "Dubai Airport (DXB)", count: "140+" },
  { area: "Deira", count: "50+" },
];

export const faqGroups = [
  {
    group: "Practical Information",
    items: [
      { q: "How do I book a car with LTS?", a: "Pick your car, choose your dates, and confirm by WhatsApp, phone, or our online booking form. We confirm availability within minutes and deliver the car to your location." },
      { q: "Do you deliver the car to me?", a: "Yes. Free delivery and collection across Dubai is included with every rental, whether you are at a hotel, residence, or the airport." },
      { q: "What are your working hours?", a: "Our booking and support team is available 24/7, every day of the year, including public holidays." },
    ],
  },
  {
    group: "Limits & Restrictions",
    items: [
      { q: "Is there a mileage limit?", a: "Daily rentals include 250 km per day. Weekly and monthly rentals include generous allowances. Extra kilometres are charged at a small fixed rate disclosed before booking." },
      { q: "What is the minimum driver age?", a: "The minimum age is 21 for most cars and 25 for exotic and luxury models, with at least one year of valid driving experience." },
      { q: "Can I drive outside Dubai?", a: "Travel within the UAE is allowed. Cross-border travel into Oman requires prior approval and additional insurance, arranged on request." },
    ],
  },
  {
    group: "Payment & Documentation",
    items: [
      { q: "Which payment methods do you accept?", a: "We accept Visa, Mastercard, cash, bank transfer, and selected cryptocurrencies. Payment is confirmed at the time of delivery." },
      { q: "What documents do tourists need?", a: "Tourists need a passport, a valid visa or entry stamp, and either a home-country licence with an International Driving Permit, or a licence from an approved country." },
      { q: "What documents do residents need?", a: "Residents need a UAE residence visa, Emirates ID, and a valid UAE driving licence." },
    ],
  },
  {
    group: "Insurance & Deposit",
    items: [
      { q: "Is insurance included?", a: "Yes. 100% comprehensive insurance is included in every rental. Optional zero-excess cover is available for complete peace of mind." },
      { q: "Do you charge a security deposit?", a: "Most cars are available with no deposit. A refundable deposit may apply to exotic models and is released back to you on return." },
      { q: "What happens in case of an accident?", a: "Call our 24/7 line immediately. We guide you through the steps and arrange a replacement vehicle so your plans are not disrupted." },
    ],
  },
];

export const blogPosts = [
  { slug: "best-roads-to-drive-supercar-dubai", title: "The Best Roads to Drive a Supercar in Dubai", excerpt: "From Jebel Hafeet to Al Qudra, here are the routes worth renting a sports car for.", date: "May 18, 2025", category: "Driving", read: "6 min" },
  { slug: "tourist-guide-renting-car-uae", title: "A Tourist's Guide to Renting a Car in the UAE", excerpt: "Documents, insurance, Salik tolls and everything first-time visitors should know.", date: "May 02, 2025", category: "Guides", read: "8 min" },
  { slug: "monthly-vs-daily-rental-which-saves", title: "Monthly vs Daily Rental: Which One Saves You More?", excerpt: "We break down the real cost difference for short trips and long stays in Dubai.", date: "Apr 21, 2025", category: "Tips", read: "5 min" },
  { slug: "top-luxury-suvs-for-desert-trips", title: "Top Luxury SUVs for Desert and City Trips", excerpt: "The most capable and comfortable SUVs in our Dubai fleet, ranked.", date: "Apr 09, 2025", category: "Fleet", read: "7 min" },
  { slug: "chauffeur-service-when-it-makes-sense", title: "When a Chauffeur Service Makes More Sense Than Driving", excerpt: "Business travel, events and airport runs where a driver is worth it.", date: "Mar 28, 2025", category: "Services", read: "4 min" },
  { slug: "electric-supercars-in-dubai", title: "Electric Performance Cars You Can Rent in Dubai", excerpt: "The new wave of EVs that deliver supercar speed with zero emissions.", date: "Mar 14, 2025", category: "Electric", read: "6 min" },
];

export const aed = (n) => "AED " + new Intl.NumberFormat("en-US").format(n);
export const carBySlug = (slug) => cars.find((c) => c.slug === slug);
export const brandName = (slug) => (brands.find((b) => b.slug === slug) || {}).name || slug;
export const categoryName = (slug) => (categories.find((c) => c.slug === slug) || {}).name || slug;
