// Central mock data for LTS Car Rental.
// Replace `image` paths with real photos in /public/cars, /public/brands etc.

export const CONTACT = {
  phone: "+971 52 237 5439",
  whatsapp: "+971 52 237 5439",
  telegram: "+971 52 237 5439",
  email: "booking@lts-car-rental.com",
  address: "Sheikh Zayed Road, Business Bay, Dubai, UAE",
  domain: "lts-car-rental.com",
};

export const categories = [
  { slug: "luxury", name: "Luxury" },
  { slug: "economy", name: "Economy" },
  { slug: "sports", name: "Sports" },
  { slug: "suv", name: "SUV" },
  { slug: "convertible", name: "Convertible" },
  { slug: "business", name: "Business" },
  { slug: "electric", name: "Electric" },
  { slug: "van", name: "Van" },
];

export const brands = [
  { slug: "lamborghini", name: "Lamborghini" },
  { slug: "ferrari", name: "Ferrari" },
  { slug: "rolls-royce", name: "Rolls-Royce" },
  { slug: "bentley", name: "Bentley" },
  { slug: "mercedes-benz", name: "Mercedes-Benz" },
  { slug: "range-rover", name: "Range Rover" },
  { slug: "porsche", name: "Porsche" },
  { slug: "bmw", name: "BMW" },
  { slug: "mclaren", name: "McLaren" , logo: "https://i.pinimg.com/originals/26/d3/94/26d394f7b8ecc31f90263bc95f9d8259.png" , logoScale: 2.8 },
  { slug: "cadillac", name: "Cadillac" , logo: "https://1000logos.net/wp-content/uploads/2020/04/Cadillac-Logo-2009.png" },
  { slug: "jetour", name: "Jetour" , logo: "https://1000logos.net/wp-content/uploads/2023/12/Jetour-Emblem.png" },
  { slug: "nissan", name: "Nissan" , logo: "https://www.logo.wine/a/logo/Nissan_USA/Nissan_USA-Logo.wine.svg" },
  { slug: "audi", name: "Audi" , logo: "https://www.logo.wine/a/logo/Audi/Audi-Logo.wine.svg" },
  { slug: "gmc", name: "GMC" , logo: "https://www.logo.wine/a/logo/GMC_(automobile)/GMC_(automobile)-Logo.wine.svg" },
];

export const bodyTypes = ["Coupe", "Sedan", "SUV", "Convertible", "Van"];
export const transmissions = ["Automatic", "Manual"];

export const cars = [
  {
    slug: "lamborghini-huracan-evo",
    name: "Lamborghini Huracán EVO",
    brand: "lamborghini",
    category: "sports",
    body: "Coupe",
    year: 2024,
    color: "Grigio Telesto",
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "5.2L V10",
    power: "640 hp",
    daily: 3200, weekly: 19500, monthly: 68000, hourly: 650,
    tag: "New Arrival",
    badge: null,
    featured: true,
    image: "https://i.pinimg.com/1200x/bd/40/32/bd40328607efd5dce564a00cdb9a76e9.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Sport exhaust", "Carbon interior", "Apple CarPlay"],
  },
  {
    slug: "ferrari-roma",
    name: "Ferrari Roma",
    brand: "ferrari",
    category: "sports",
    body: "Coupe",
    year: 2023,
    color: "Rosso Corsa",
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "3.9L V8",
    power: "612 hp",
    daily: 2900, weekly: 17800, monthly: 62000, hourly: 590,
    tag: null, badge: "-10%", oldDaily: 3220,
    featured: true,
    image: "https://i.pinimg.com/736x/de/90/b1/de90b11440a76d213480232629a874af.jpg",
    pos: "center 85%",
    features: ["Full insurance included", "Free delivery in Dubai", "Launch control", "Premium audio"],
  },
  {
    slug: "rolls-royce-ghost",
    name: "Rolls-Royce Ghost",
    brand: "rolls-royce",
    category: "luxury",
    body: "Sedan",
    year: 2024,
    color: "Arctic White",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "6.75L V12",
    power: "563 hp",
    daily: 4500, weekly: 28000, monthly: 95000, hourly: 900,
    tag: null, badge: null,
    featured: true,
    image: "https://i.pinimg.com/736x/a4/1d/6d/a41d6d2cd1109017fe2797d4a12db509.jpg",
    features: ["Chauffeur available", "Starlight headliner", "Full insurance included", "Rear lounge seating"],
  },
  {
    slug: "bentley-continental-gt",
    name: "Bentley Continental GT",
    brand: "bentley",
    category: "luxury",
    body: "Coupe",
    year: 2023,
    color: "Beluga Black",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.0L V8",
    power: "542 hp",
    daily: 2600, weekly: 15800, monthly: 54000, hourly: 520,
    tag: null, badge: "-15%", oldDaily: 3060,
    featured: true,
    image: "https://i.pinimg.com/1200x/b1/37/75/b13775af7083f664b0e9bbac416e9e0e.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Rotating display", "Naim audio"],
  },
  {
    slug: "mercedes-g63-amg",
    name: "Mercedes-Benz G63 AMG",
    brand: "mercedes-benz",
    category: "suv",
    body: "SUV",
    year: 2024,
    color: "Obsidian Black",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.0L V8 Biturbo",
    power: "585 hp",
    daily: 2200, weekly: 13500, monthly: 46000, hourly: 450,
    tag: "Available now", badge: null,
    featured: true,
    image: "https://i.pinimg.com/1200x/f9/a3/b5/f9a3b57c453f38df2d8aa24f97ca5955.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "AMG performance pack", "Burmester sound"],
  },
  {
    slug: "range-rover-autobiography",
    name: "Range Rover Autobiography",
    brand: "range-rover",
    category: "suv",
    body: "SUV",
    year: 2024,
    color: "Santorini Black",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.4L V8",
    power: "523 hp",
    daily: 1600, weekly: 9800, monthly: 33000, hourly: 320,
    tag: null, badge: null,
    featured: true,
    image: "https://i.pinimg.com/736x/96/6c/c8/966cc8a13934fc95b36879c3d77084da.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Massage seats", "Meridian audio"],
  },
  {
    slug: "porsche-911-carrera",
    name: "Porsche 911 Carrera S",
    brand: "porsche",
    category: "sports",
    body: "Coupe",
    year: 2023,
    color: "GT Silver",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "3.0L Flat-6",
    power: "443 hp",
    daily: 1800, weekly: 11000, monthly: 38000, hourly: 360,
    tag: null, badge: "-10%", oldDaily: 2000,
    featured: false,
    image: "https://i.pinimg.com/736x/e4/0c/ea/e40cea198bba8c5ec195208a2d0aaff0.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Sport Chrono", "Bose audio"],
  },
  {
    slug: "bmw-m4-competition",
    name: "BMW M4 Competition",
    brand: "bmw",
    category: "sports",
    body: "Coupe",
    year: 2024,
    color: "Isle of Man Green",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "3.0L Twin-Turbo",
    power: "503 hp",
    daily: 1200, weekly: 7300, monthly: 25000, hourly: 240,
    tag: "Available now", badge: null,
    featured: false,
    image: "https://i.pinimg.com/736x/eb/d5/0a/ebd50aea2e9aba08c3f5ee7fa6612e0b.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "M Sport seats", "Harman Kardon"],
  },
  {
    slug: "mercedes-s500",
    name: "Mercedes-Benz S500",
    brand: "mercedes-benz",
    category: "business",
    body: "Sedan",
    year: 2024,
    color: "Selenite Grey",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "3.0L Inline-6",
    power: "429 hp",
    daily: 1100, weekly: 6700, monthly: 23000, hourly: 220,
    tag: null, badge: null,
    featured: false,
    image: "https://i.pinimg.com/1200x/44/4c/67/444c67984dc03ea63740e13e898059e7.jpg",
    features: ["Chauffeur available", "Full insurance included", "Rear executive seats", "Free delivery in Dubai"],
  },
  {
    slug: "tesla-model-s-plaid",
    name: "Tesla Model S Plaid",
    brand: "bmw",
    category: "electric",
    body: "Sedan",
    year: 2024,
    color: "Pearl White",
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    engine: "Tri-Motor EV",
    power: "1020 hp",
    daily: 900, weekly: 5500, monthly: 19000, hourly: 180,
    tag: "New Arrival", badge: null,
    featured: false,
    image: "https://i.pinimg.com/1200x/3e/63/5a/3e635a2801b0f92e928c1772e765c484.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Autopilot", "Free supercharging"],
  },
  {
    slug: "mercedes-maybach-s680",
    name: "Mercedes-Maybach S680",
    brand: "mercedes-benz",
    category: "luxury",
    body: "Sedan",
    year: 2024,
    color: "Emerald Green",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "6.0L V12",
    power: "612 hp",
    daily: 2400, weekly: 14600, monthly: 50000, hourly: 480,
    tag: null, badge: null,
    featured: false,
    image: "https://i.pinimg.com/1200x/e1/f8/eb/e1f8ebd351104e37f4f9bd7f7469ca45.jpg",
    features: ["Chauffeur available", "Executive rear seats", "Full insurance included", "Champagne fridge"],
  },
  {
    slug: "toyota-camry",
    name: "Toyota Camry",
    brand: "bmw",
    category: "economy",
    body: "Sedan",
    year: 2024,
    color: "Silver",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "2.5L Inline-4",
    power: "203 hp",
    daily: 180, weekly: 1050, monthly: 3200, hourly: 45,
    tag: null, badge: "-20%", oldDaily: 225,
    featured: false,
    image: "https://i.pinimg.com/736x/d7/02/90/d70290e501fffcf4d001a753f253b2d0.jpg",
    features: ["Full insurance included", "Free delivery in Dubai", "Apple CarPlay", "Fuel efficient"],
  },
  {
    slug: "mercedes-v-class",
    name: "Mercedes-Benz V-Class",
    brand: "mercedes-benz",
    category: "van",
    body: "Van",
    year: 2024,
    color: "Cavansite Blue",
    seats: 7,
    transmission: "Automatic",
    fuel: "Diesel",
    engine: "2.0L Diesel",
    power: "237 hp",
    daily: 700, weekly: 4200, monthly: 14500, hourly: 140,
    tag: null, badge: null,
    featured: false,
    image: "https://i.pinimg.com/1200x/9e/58/83/9e58834c84f784fbeefe0dec25f5e414.jpg",
    features: ["Chauffeur available", "7 seats", "Full insurance included", "Captain seats"],
  },
  {
    slug: "ferrari-portofino-m",
    name: "Ferrari Portofino M",
    brand: "ferrari",
    category: "convertible",
    body: "Convertible",
    year: 2023,
    color: "Blu Corsa",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "3.9L V8",
    power: "612 hp",
    daily: 3100, weekly: 18900, monthly: 65000, hourly: 620,
    tag: null, badge: null,
    featured: false,
    image: "https://i.pinimg.com/1200x/36/4d/1e/364d1e7acf9536c0fef75884f086f523.jpg",
    features: ["Retractable hardtop", "Full insurance included", "Free delivery in Dubai", "Magneride"],
  },
  {
    slug: "lamborghini-urus",
    name: "Lamborghini Urus",
    brand: "lamborghini",
    category: "suv",
    body: "SUV",
    year: 2024,
    color: "Giallo Auge",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.0L V8 Biturbo",
    power: "657 hp",
    daily: 2700, weekly: 16400, monthly: 56000, hourly: 540,
    tag: "Available now", badge: null,
    featured: false,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/52-1024x768-1.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/52-1024x768-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/3-4.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/0-2.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/1-3.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "Sport mode", "Bang & Olufsen"],
  },
  {
    slug: "ferrari-f8",
    name: "Ferrari F8 Tributo",
    brand: "ferrari",
    category: "sports",
    body: "Coupe",
    year: 2025,
    color: "Rosso Corsa",
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "3.9L V8",
    power: "710 hp",
    daily: 3800, weekly: 22800, monthly: 76000, hourly: 760,
    tag: "New Arrival",
    badge: null,
    featured: true,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/01/62b2dc40-afa3-4f3d-93f8-0e1d2e9231c8-1024x576.jpg",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/01/62b2dc40-afa3-4f3d-93f8-0e1d2e9231c8-1024x576.jpg", "https://lts-car-rental.com/wp-content/uploads/2026/02/4aa27bcd-42e7-48ad-85c1-058c747f26ce-1024x576-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/9a24381c-0851-4cdb-94d5-e3be6200e6d9-1024x576-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/62b2dc40-afa3-4f3d-93f8-0e1d2e9231c8-1024x576-1.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "mclaren-artura",
    name: "McLaren Artura",
    brand: "mclaren",
    category: "sports",
    body: "Coupe",
    year: 2025,
    color: "Silver",
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "3.0L V6 Hybrid",
    power: "671 hp",
    daily: 3600, weekly: 21600, monthly: 72000, hourly: 720,
    tag: "New Arrival",
    badge: null,
    featured: true,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/0-6.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/0-6.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/0-6.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/1-7.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/2-6.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "ferrari-purosangue-black",
    name: "Ferrari Purosangue",
    brand: "ferrari",
    category: "suv",
    body: "SUV",
    year: 2025,
    color: "Nero",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "6.5L V12",
    power: "715 hp",
    daily: 4800, weekly: 28800, monthly: 96000, hourly: 960,
    tag: "New Arrival",
    badge: null,
    featured: true,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/01/47046987-363d-4e62-afa0-8575a1902ccd-930x620.jpg",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/01/47046987-363d-4e62-afa0-8575a1902ccd-930x620.jpg", "https://lts-car-rental.com/wp-content/uploads/2026/02/19b7a760-8ec5-4f96-85e0-e565a2c457b2-930x620-1-300x200.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/53834e25-c66d-493d-b65e-726bea5d3509-930x620-1-300x200.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/47046987-363d-4e62-afa0-8575a1902ccd-930x620-1-300x200.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "mercedes-c350",
    name: "Mercedes-Benz C350",
    brand: "mercedes-benz",
    category: "business",
    body: "Sedan",
    year: 2025,
    color: "White",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "2.0L Turbo",
    power: "255 hp",
    daily: 650, weekly: 3900, monthly: 13000, hourly: 130,
    tag: "New Arrival",
    badge: null,
    featured: false,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/13-e1778151054328-768x633.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/13-e1778151054328-768x633.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/88.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/89.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/90.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "ferrari-purosangue-red",
    name: "Ferrari Purosangue",
    brand: "ferrari",
    category: "suv",
    body: "SUV",
    year: 2025,
    color: "Rosso",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "6.5L V12",
    power: "715 hp",
    daily: 4800, weekly: 28800, monthly: 96000, hourly: 960,
    tag: "New Arrival",
    badge: null,
    featured: false,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/01/a363f559-a012-4489-a7b2-9176896a12df-819x1024.jpg",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/01/a363f559-a012-4489-a7b2-9176896a12df-819x1024.jpg", "https://lts-car-rental.com/wp-content/uploads/2026/02/a363f559-a012-4489-a7b2-9176896a12df.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/3da4db5d-0150-4c02-a365-803322a06c2c-819x1024-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/930efbd1-68a3-4251-8d8c-f10337550e00-819x1024-1.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "lamborghini-svj",
    name: "Lamborghini Aventador SVJ",
    brand: "lamborghini",
    category: "sports",
    body: "Coupe",
    year: 2025,
    color: "Verde",
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "6.5L V12",
    power: "759 hp",
    daily: 5500, weekly: 33000, monthly: 110000, hourly: 1100,
    tag: "New Arrival",
    badge: null,
    featured: true,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/0000-1.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/0000-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/88-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/89-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/89-1.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  
  {
    slug: "bmw-m8",
    name: "BMW M8 Competition",
    brand: "bmw",
    category: "sports",
    body: "Coupe",
    year: 2025,
    color: "Black",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.4L V8",
    power: "617 hp",
    daily: 1600, weekly: 9600, monthly: 32000, hourly: 320,
    tag: "New Arrival",
    badge: null,
    featured: false,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/1-5dfd3ea-d5f9-4545-a747-6ece05883830-930x620-1.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/1-5dfd3ea-d5f9-4545-a747-6ece05883830-930x620-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/74f1ed43-f6ea-48d6-8c82-c9d4d8a2d474-1024x576-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/6f64d152-4abf-4fb2-b896-48083f62a609-930x620-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/1-5dfd3ea-d5f9-4545-a747-6ece05883830-930x620-1.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "bmw-m5-g90",
    name: "BMW M5 G90",
    brand: "bmw",
    category: "business",
    body: "Sedan",
    year: 2025,
    color: "Grey",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.4L V8 Hybrid",
    power: "717 hp",
    daily: 1500, weekly: 9000, monthly: 30000, hourly: 300,
    tag: "New Arrival",
    badge: null,
    featured: true,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-09-at-7.21.57-PM-1024x576-1.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-09-at-7.21.57-PM-1024x576-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-09-at-7.21.57-PM-1-1024x576-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-09-at-7.21.56-PM-930x620-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-09-at-7.21.55-PM-1-1024x664-1.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "cadillac-escalade-v",
    name: "Cadillac Escalade-V",
    brand: "cadillac",
    category: "suv",
    body: "SUV",
    year: 2025,
    color: "Black",
    seats: 7,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "6.2L V8",
    power: "682 hp",
    daily: 1700, weekly: 10200, monthly: 34000, hourly: 340,
    tag: "New Arrival",
    badge: null,
    featured: false,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/6-1.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/6-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/61.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/62.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/63.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "jetour-t2-white",
    name: "Jetour T2",
    brand: "jetour",
    category: "suv",
    body: "SUV",
    year: 2025,
    color: "White",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "2.0L Turbo",
    power: "254 hp",
    daily: 500, weekly: 3000, monthly: 10000, hourly: 100,
    tag: "New Arrival",
    badge: null,
    featured: false,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/0000000000000000000000000.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/0000000000000000000000000.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/9.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/4.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/3.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "bmw-420",
    name: "BMW 420i",
    brand: "bmw",
    category: "luxury",
    body: "Coupe",
    year: 2025,
    color: "White",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "2.0L Turbo",
    power: "184 hp",
    daily: 700, weekly: 4200, monthly: 14000, hourly: 140,
    tag: "New Arrival",
    badge: null,
    featured: false,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/3646928e-de9e-46f8-922a-f7416a526abd-819x1024-1.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/3646928e-de9e-46f8-922a-f7416a526abd-819x1024-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/814e2a95-835c-4330-8c07-c996b7a9d654-819x1024-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/3646928e-de9e-46f8-922a-f7416a526abd-819x1024-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/66412afe-211e-41c6-ba57-23f1561135cb-819x1024-1.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "nissan-patrol-nismo",
    name: "Nissan Patrol NISMO",
    brand: "nissan",
    category: "suv",
    body: "SUV",
    year: 2025,
    color: "White",
    seats: 7,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "5.6L V8",
    power: "428 hp",
    daily: 1200, weekly: 7200, monthly: 24000, hourly: 240,
    tag: "New Arrival",
    badge: null,
    featured: false,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/DSC06831-683x1024-1.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/DSC06831-683x1024-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/DSC06823-683x1024-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/Untitled-design-768x1024-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/Untitled-design-768x1024-1.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "lamborghini-sto",
    name: "Lamborghini Hurac\u00e1n STO",
    brand: "lamborghini",
    category: "sports",
    body: "Coupe",
    year: 2025,
    color: "Blu",
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "5.2L V10",
    power: "631 hp",
    daily: 4200, weekly: 25200, monthly: 84000, hourly: 840,
    tag: "New Arrival",
    badge: null,
    featured: true,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/000-1.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/000-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/44-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/45-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/46-1.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "porche-gt3",
    name: "Porsche 911 GT3",
    brand: "porsche",
    category: "sports",
    body: "Coupe",
    year: 2025,
    color: "White",
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.0L Flat-6",
    power: "510 hp",
    daily: 2800, weekly: 16800, monthly: 56000, hourly: 560,
    tag: "New Arrival",
    badge: null,
    featured: false,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/8-3.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/8-3.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/11-4.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/10-2.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/9-4.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "ferrari-12-cilindri",
    name: "Ferrari 12Cilindri",
    brand: "ferrari",
    category: "sports",
    body: "Coupe",
    year: 2025,
    color: "Giallo",
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "6.5L V12",
    power: "819 hp",
    daily: 5200, weekly: 31200, monthly: 104000, hourly: 1040,
    tag: "New Arrival",
    badge: null,
    featured: true,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/05/6dd4d5ad-eba3-405f-9305-84b7c3e55b9f-1536x1025.jpg",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/05/6dd4d5ad-eba3-405f-9305-84b7c3e55b9f-1536x1025.jpg", "https://lts-car-rental.com/wp-content/uploads/2026/05/531ab53a-cc7a-4b17-8e7c-6d6b809ee6f1-1.jpg", "https://lts-car-rental.com/wp-content/uploads/2026/05/683a7df0-1918-4670-921e-a11705eaf733-1.jpg", "https://lts-car-rental.com/wp-content/uploads/2026/05/eedd41d3-5ad9-4f33-a392-6536c8b77e61-1.jpg"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "audi-a3",
    name: "Audi A3",
    brand: "audi",
    category: "economy",
    body: "Sedan",
    year: 2025,
    color: "Grey",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "2.0L Turbo",
    power: "201 hp",
    daily: 280, weekly: 1680, monthly: 5600, hourly: 60,
    tag: "New Arrival",
    badge: null,
    featured: false,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/0-5.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/0-5.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/2-5.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/3-7.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/1-6.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "gmc-yukon",
    name: "GMC Yukon",
    brand: "gmc",
    category: "suv",
    body: "SUV",
    year: 2025,
    color: "Black",
    seats: 7,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "5.3L V8",
    power: "355 hp",
    daily: 850, weekly: 5100, monthly: 17000, hourly: 170,
    tag: "New Arrival",
    badge: null,
    featured: false,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/02/111-1.webp",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/02/111-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/110.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/112-1.webp", "https://lts-car-rental.com/wp-content/uploads/2026/02/113-1.webp"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
  {
    slug: "gmc-yukon-2026",
    name: "GMC Yukon 2026",
    brand: "gmc",
    category: "suv",
    body: "SUV",
    year: 2025,
    color: "White",
    seats: 7,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "6.2L V8",
    power: "420 hp",
    daily: 950, weekly: 5700, monthly: 19000, hourly: 190,
    tag: "New Arrival",
    badge: null,
    featured: false,
    image: "https://lts-car-rental.com/wp-content/uploads/2026/06/Screenshot-2026-06-02-073246.png",
    images: ["https://lts-car-rental.com/wp-content/uploads/2026/06/Screenshot-2026-06-02-073246.png", "https://lts-car-rental.com/wp-content/uploads/2026/06/Screenshot-2026-06-02-073525.png", "https://lts-car-rental.com/wp-content/uploads/2026/06/Screenshot-2026-06-02-073451.png", "https://lts-car-rental.com/wp-content/uploads/2026/06/Screenshot-2026-06-02-073407-1.png"],
    features: ["Full insurance included", "Free delivery in Dubai", "24/7 support", "Apple CarPlay"],
  },
];

export const reviews = [
  { name: "Omar Al-Farsi", date: "May 2025", rating: 5, text: "Booked the Huracán for a weekend in Dubai. Car was spotless and delivered to my hotel on time. The whole process took ten minutes." },
  { name: "Sophie Laurent", date: "Apr 2025", rating: 5, text: "Rented a Range Rover for a month while relocating. No deposit, full insurance, and the team handled everything over WhatsApp." },
  { name: "David Chen", date: "Apr 2025", rating: 4, text: "Smooth airport transfer and a clean G63 waiting at arrivals. Pricing was transparent with no surprise charges at return." },
  { name: "Aisha Rahman", date: "Mar 2025", rating: 5, text: "Chauffeur service for a business event was flawless. Professional driver, immaculate S-Class, and easy online booking." },
  { name: "Marco Rossi", date: "Mar 2025", rating: 5, text: "Long-term lease on a Continental GT. Best rate I found in the city and free delivery across Dubai every service visit." },
  { name: "Liam Walsh", date: "Feb 2025", rating: 4, text: "Quick weekend rental on the 911. Easy pickup in Dubai Marina and the car drove like new. Will book again next trip." },
];

export const locations = [
  { area: "Dubai Marina", count: "120+" },
  { area: "Downtown Dubai", count: "95+" },
  { area: "Business Bay", count: "110+" },
  { area: "Palm Jumeirah", count: "70+" },
  { area: "Jumeirah Beach Residence", count: "85+" },
  { area: "DIFC", count: "60+" },
  { area: "Dubai Airport (DXB)", count: "140+" },
  { area: "Deira", count: "50+" },
];

export const faqGroups = [
  {
    group: "Practical Information",
    items: [
      { q: "How do I book a car with LTS?", a: "Pick your car, choose your dates, and confirm by WhatsApp, phone, or our online booking form. We confirm availability within minutes and deliver the car to your location." },
      { q: "Do you deliver the car to me?", a: "Yes. Free delivery and collection across Dubai is included with every rental, whether you are at a hotel, residence, or the airport." },
      { q: "What are your working hours?", a: "Our booking and support team is available 24/7, every day of the year, including public holidays." },
    ],
  },
  {
    group: "Limits & Restrictions",
    items: [
      { q: "Is there a mileage limit?", a: "Daily rentals include 250 km per day. Weekly and monthly rentals include generous allowances. Extra kilometres are charged at a small fixed rate disclosed before booking." },
      { q: "What is the minimum driver age?", a: "The minimum age is 21 for most cars and 25 for exotic and luxury models, with at least one year of valid driving experience." },
      { q: "Can I drive outside Dubai?", a: "Travel within the UAE is allowed. Cross-border travel into Oman requires prior approval and additional insurance, arranged on request." },
    ],
  },
  {
    group: "Payment & Documentation",
    items: [
      { q: "Which payment methods do you accept?", a: "We accept Visa, Mastercard, cash, bank transfer, and selected cryptocurrencies. Payment is confirmed at the time of delivery." },
      { q: "What documents do tourists need?", a: "Tourists need a passport, a valid visa or entry stamp, and either a home-country licence with an International Driving Permit, or a licence from an approved country." },
      { q: "What documents do residents need?", a: "Residents need a UAE residence visa, Emirates ID, and a valid UAE driving licence." },
    ],
  },
  {
    group: "Insurance & Deposit",
    items: [
      { q: "Is insurance included?", a: "Yes. 100% comprehensive insurance is included in every rental. Optional zero-excess cover is available for complete peace of mind." },
      { q: "Do you charge a security deposit?", a: "Most cars are available with no deposit. A refundable deposit may apply to exotic models and is released back to you on return." },
      { q: "What happens in case of an accident?", a: "Call our 24/7 line immediately. We guide you through the steps and arrange a replacement vehicle so your plans are not disrupted." },
    ],
  },
];

export const blogPosts = [
  { slug: "best-roads-to-drive-supercar-dubai", title: "The Best Roads to Drive a Supercar in Dubai", excerpt: "From Jebel Hafeet to Al Qudra, here are the routes worth renting a sports car for.", date: "May 18, 2025", category: "Driving", read: "6 min" },
  { slug: "tourist-guide-renting-car-uae", title: "A Tourist's Guide to Renting a Car in the UAE", excerpt: "Documents, insurance, Salik tolls and everything first-time visitors should know.", date: "May 02, 2025", category: "Guides", read: "8 min" },
  { slug: "monthly-vs-daily-rental-which-saves", title: "Monthly vs Daily Rental: Which One Saves You More?", excerpt: "We break down the real cost difference for short trips and long stays in Dubai.", date: "Apr 21, 2025", category: "Tips", read: "5 min" },
  { slug: "top-luxury-suvs-for-desert-trips", title: "Top Luxury SUVs for Desert and City Trips", excerpt: "The most capable and comfortable SUVs in our Dubai fleet, ranked.", date: "Apr 09, 2025", category: "Fleet", read: "7 min" },
  { slug: "chauffeur-service-when-it-makes-sense", title: "When a Chauffeur Service Makes More Sense Than Driving", excerpt: "Business travel, events and airport runs where a driver is worth it.", date: "Mar 28, 2025", category: "Services", read: "4 min" },
  { slug: "electric-supercars-in-dubai", title: "Electric Performance Cars You Can Rent in Dubai", excerpt: "The new wave of EVs that deliver supercar speed with zero emissions.", date: "Mar 14, 2025", category: "Electric", read: "6 min" },
];

export const aed = (n) => "AED " + new Intl.NumberFormat("en-US").format(n);
export const carBySlug = (slug) => cars.find((c) => c.slug === slug);
export const brandName = (slug) => (brands.find((b) => b.slug === slug) || {}).name || slug;
export const categoryName = (slug) => (categories.find((c) => c.slug === slug) || {}).name || slug;

// Blog article bodies (generic editorial copy for the demo)
export const blogBodies = {
  "best-roads-to-drive-supercar-dubai": [
    "Dubai and the wider Emirates offer some of the most rewarding driving roads in the region, combining smooth tarmac, dramatic scenery and long open stretches where a performance car finally makes sense. Whether you are chasing mountain switchbacks or wide desert highways, the right route turns a rental into an experience.",
    "For newcomers, the appeal is simple: well-maintained roads, clear signage and a culture that genuinely appreciates fine machinery. Plan your drive for early morning or late afternoon to avoid the midday heat and the heaviest traffic, and always keep an eye on posted speed limits and Salik toll gates.",
    "Before you set off, make sure your rental includes full insurance and that you are comfortable with the car's size and power. Our team can recommend the ideal model for the route you have in mind and deliver it anywhere in the city.",
  ],
  "tourist-guide-renting-car-uae": [
    "Renting a car as a visitor in the UAE is refreshingly straightforward, but a little preparation goes a long way. Most rentals require a valid passport, a visa or entry stamp, and either a home-country licence with an International Driving Permit or a licence from an approved country.",
    "Understand the small costs that add up: Salik toll gates are automatic and charged per crossing, fuel is inexpensive by global standards, and parking in busy districts is often paid via app. A security deposit is standard and is released after the car is returned in good condition.",
    "Choose a provider that includes insurance, offers transparent pricing and delivers the car to your hotel or the airport. That way you can skip the counter queues and start your trip the moment you land.",
  ],
  "monthly-vs-daily-rental-which-saves": [
    "The right rental length depends entirely on how you plan to use the car. Daily rates suit short visits and one-off occasions, while weekly and monthly packages are designed for residents, long stays and anyone who needs a car on hand every day.",
    "As a rule of thumb, the longer the term, the lower the effective daily cost. Monthly rentals also bundle in benefits like generous mileage allowances and simpler paperwork, which makes them popular with professionals on assignment in the city.",
    "If you are unsure, tell us your dates and how far you expect to drive. We will put together a package that gives you the best value rather than pushing you toward a fixed plan.",
  ],
  "top-luxury-suvs-for-desert-trips": [
    "A luxury SUV is the most versatile way to explore the Emirates, comfortable enough for the city and capable enough for a weekend beyond it. The best options pair a commanding driving position with genuine off-tarmac ability and a cabin that keeps everyone relaxed.",
    "Look for strong air-conditioning, generous boot space and a smooth ride for long highway stretches. If any part of your trip leaves the paved road, ask about ground clearance and drive modes before you book.",
    "From family-friendly cruisers to high-performance flagships, our fleet covers the full range. Let us know your plans and we will match you with an SUV that fits both the terrain and the occasion.",
  ],
  "chauffeur-service-when-it-makes-sense": [
    "Driving yourself is part of the fun, but there are times when a professional chauffeur is the smarter choice. Airport arrivals, business meetings, weddings and long evenings out are all easier when someone else handles the traffic and the parking.",
    "A chauffeur service also removes the stress of navigating an unfamiliar city, letting you focus on work or simply enjoy the ride. Discretion, punctuality and a spotless vehicle are the standards you should expect.",
    "You can switch between self-drive and chauffeured travel depending on the day. Tell us your schedule and we will arrange the right car and driver for each part of your trip.",
  ],
  "electric-supercars-in-dubai": [
    "Electric performance cars have arrived in force, and Dubai is one of the best places to experience them. Instant torque, near-silent acceleration and cutting-edge technology make them a genuinely different kind of thrill.",
    "Charging infrastructure across the city has expanded quickly, so range anxiety is far less of a concern than it once was. Many models now cover long distances comfortably and top up rapidly at public stations.",
    "If you are curious about making the switch, an electric rental is the perfect way to try before you commit. Ask us which models are available and we will help you plan a route with charging in mind.",
  ],
};

export function blogBySlug(slug) {
  return blogPosts.find((p) => p.slug === slug);
}
